language: node_js

services:
  - docker

script:
  - npm run test

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(feature/travis-ci|staging|release|master)$
