language: node_js

services:
  - docker

script:
  - npm run test
  - docker build -t openstad/auth:test .

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(staging|release|master)$
